- name: Make gradlew executable
        run: chmod +x gradlew

      # Creates your .env file
      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      # Creates your google-services.json file automatically on GitHub
      - name: Create Google Services JSON
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --stacktrace